version: '3.8'  # Docker Compose 파일 버전

services:
  data-generator:  # 항공편 정보를 가져오는 Python 스크립트를 실행하는 컨테이너
    build: ./data-generator  # data-generator 폴더의 Dockerfile을 기준으로 이미지 빌드
    volumes:
      - ./shared-data:/app/output  # 공유 폴더: JSON 및 HTML 파일을 이 경로에 저장
    restart: always  # 컨테이너가 중단되면 항상 재시작

  webserver:  # 웹 서버 역할 (Nginx로 정적 파일 제공)
    build: ./webserver  # webserver 폴더의 Dockerfile을 기준으로 이미지 빌드
    ports:
      - "8080:80"  # 호스트의 80번 포트를 컨테이너의 80번 포트에 연결 (웹에서 접속 가능)
    volumes:
      - ./shared-data:/usr/share/nginx/html/data:ro  # 공유 폴더를 Nginx의 /data 경로에 마운트 (읽기 전용)
      - ./webserver/default.conf:/etc/nginx/conf.d/default.conf  # 커스텀 Nginx 설정 적용
    depends_on:
      - data-generator  # data-generator 서비스가 실행된 후 webserver가 실행되도록 설정

